package dev.hidgamepad.core.profile

import dev.hidgamepad.core.layout.ControlSpec
import dev.hidgamepad.core.layout.LayoutProfile
import kotlinx.serialization.json.Json
import java.util.Locale

/** JSON (de)serialization for layout profiles — persistence and share-sheet export. */
object ProfileJson {

    val json: Json = Json {
        prettyPrint = true
        ignoreUnknownKeys = true
        encodeDefaults = true
    }

    fun encode(profile: LayoutProfile): String = json.encodeToString(LayoutProfile.serializer(), profile)

    fun decode(text: String): LayoutProfile = json.decodeFromString(LayoutProfile.serializer(), text)
}

/**
 * Exports a calibrated profile's control positions as an OpenSCAD config
 * fragment (millimetres from the screen's top-left corner), closing the loop
 * between app calibration and the printable case (`case/config.scad`).
 */
object CaseExport {

    fun toScadFragment(profile: LayoutProfile): String {
        val screen = requireNotNull(profile.screen) {
            "Profile has no screen metadata; calibrate on-device before exporting"
        }
        val mmPerPxX = 25.4f / screen.xdpi
        val mmPerPxY = 25.4f / screen.ydpi
        fun xMm(v: Float) = "%.2f".format(Locale.ROOT, v * screen.widthPx * mmPerPxX)
        fun yMm(v: Float) = "%.2f".format(Locale.ROOT, v * screen.heightPx * mmPerPxY)

        val buttons = StringBuilder("flex_buttons = [\n")
        val toggles = StringBuilder("toggles = [\n")
        val sticks = StringBuilder("stick_wells = [\n")
        val triggers = StringBuilder("trigger_mounts = [\n")
        profile.controls.forEach { c ->
            val row = "    [${xMm(c.center.x)}, ${yMm(c.center.y)}, \"${c.label}\"],\n"
            when (c) {
                is ControlSpec.ButtonZone -> buttons.append(row)
                is ControlSpec.ToggleZone -> toggles.append(row)
                is ControlSpec.StickZone -> sticks.append(row)
                is ControlSpec.TriggerZone -> triggers.append(row)
                is ControlSpec.DpadZone -> buttons.append(row)
            }
        }
        return buildString {
            appendLine("// Generated by the HID Gamepad app from profile \"${profile.name}\"")
            appendLine("// Coordinates are millimetres from the screen's top-left corner.")
            append(buttons).appendLine("];")
            append(toggles).appendLine("];")
            append(sticks).appendLine("];")
            append(triggers).appendLine("];")
        }
    }
}
